name: map
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1  # Ensure you have the latest version
  image_picker: 1.1.1
  firebase_storage: 11.0.6
  intl: ^0.17.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
